--계정생성
CREATE USER c##demo IDENTIFIED BY demo1234
    DEFAULT TABLESPACE users
    TEMPORARY TABLESPACE temp
    PROFILE DEFAULT;
--권한부여
GRANT CONNECT, RESOURCE TO c##demo;
GRANT CREATE VIEW, CREATE SYNONYM TO c##demo;
GRANT UNLIMITED TABLESPACE TO c##demo;
--락 풀기
ALTER USER c##demo ACCOUNT UNLOCK;